### ISSUE TITLE
fossho.st is down

### ISSUE THREAD

**Issue by bf** [chaotic-aur/chaotic-uptimes#173] opened 2023-03-01 10:29 UTC
My request to https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst resolves to https://mirrors.fossho.st/garuda/repos/chaotic-aur/chaotic-keyring.pkg.tar.zst which shows:

```
Error 503 Backend unavailable, connection timeout
Backend unavailable, connection timeout

Error 54113
Details: cache-fra-eddf8230135-FRA 1677666500 2724824364

Varnish cache server
```

**Comment by dr460nf1r3** [comment] 2023-03-02 06:49
Closing as duplicate of https://github.com/chaotic-aur/chaotic-uptimes/issues/175#issue-1605919383. Thanks for reporting!

**Closed by dr460nf1r3** 2023-03-02 06:49 UTC
Labels: bug
